### ISSUE TITLE
[iOS/macOS] Swift package manager support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1012]
swift-tools-version:5.3 now supports binary target, it needs xcframework

Todo:

- [ ] build and upload xcframework to github release page
- [ ] update Package.swift to use `SwiftProtobuf` fork (dynamic target)

souce: https://developer.apple.com/videos/play/wwdc2020/10147/

**Comment by ronaldmannak** [comment]
Package manager support would be great for new projects. Has someone already taken a stab at it? If not, happy to help out. I haven't created any Swift packages before, but I have created CocoaPods before.

**Comment by hewigovens** [comment]
@ronaldmannak we're waiting for Xcode GM build, we already have [a script](https://github.com/trustwallet/wallet-core/blob/master/tools/ios-build-framework) to build `xcframework` if you'd like to try out

**Comment by ronaldmannak** [comment]
Beta 2 seems quite stable. I could image working on the package manager and (if needed) update it if future version break anything, but I understand your approach.

The script is indeed super helpful, that is a perfect alternative until the Swift package. I hadn't seen that. Thanks!

**Comment by hewigovens** [comment]
Once you build the xcframework, should be easy to add a Package.swift to consume it, let me know if that works

**Comment by ronaldmannak** [comment]
@hewigovens FYI: You can't CocoaPods on the Apple DTK yet, as some gems seem to assume MacOS always equals Intel x64.

That means that for now, you have to initialize wallet-core on an x64 Mac.

**Comment by hewigovens** [comment]
Thanks for the info, I think you can build xcframework on DTK(I fixed Xcode 12 building errors), only one problem I know is that SwiftProtobuf doesn't have dynamic library via SPM, you need to fork or manually build it

**Comment by ronaldmannak** [comment]
Thanks @hewigovens. Has anyone tried to add a MacOS framework target? I assume it's not a big difference from the iOS script. If not, I'll add it.

**Comment by hewigovens** [comment]
The script has code to build mac and catalyst

**Comment by ronaldmannak** [comment]
Thanks @hewigovens. I see there are indeed Mac targets (catalyst and non-catalyst) in tools/iOS-build-framework shell script. 

What would it take to have Xcode 12 create a universal (ARM/x64) TrustWalletCore framework? For one cmake doesn't seem to like the spaces in "Xcode beta 2" directory name.

I've tried to recreate the project by hand in Xcode 12, but that's probably way more complicated than updating the build scripts. Do you have any pointers in the right direction?

**Comment by hewigovens** [comment]
I think the first step is to install all the prerequisites listed here (https://developer.trustwallet.com/wallet-core/developing-the-library/building#prerequisites-on-macos), android tools can be ignored, make sure you can successfully run `./bootstrap.sh`

then you should able to create the framework: `tools/ios-build-framework` (located in `build/ios-frameworks/TrustWalletCore.xcframework`)

Note: You also need to build `SwiftProtobuf` (with `Build for Distribution` true) as a dynamic framework (the only wallet core swift dependency)

**Comment by hewigovens** [comment]
Haven't got the DTK to test the steps I mentioned above

**Comment by ronaldmannak** [comment]
Yes, I've tried to follow the steps. The scripts don't work since many of the gem and brew packages can't be installed on the DTK yet, and Xcode 12 Beta isn't supported yet as described in issue #1039. 

The way I've tried to make it work is to run the bootstrap script on an Intel Mac using Xcode 11 and then basically manually rebuild the project in Xcode 12 on ARM. Swift-protobuf and SwiftLint can easily be added using Swift Package Manager. Libprotobuf and libtrezor-crypto can be compiled manually after opening the workspace created on Xcode 11 on Xcode12/ARM. There are many manual tweaks needed so it's far from optimal.

As I mentioned in #1039 I think it would make sense to prioritize building on Xcode 12 beta on Intel. I think that would be the fastest and least intrusive.

**Comment by saltyskip** [comment]
Any updates on this? Has anyone been able to successfully deploy trust core as a swift package?

**Comment by hewigovens** [comment]
@saltyskip we're waiting for Xcode GM release

**Comment by erwinmaza** [comment]
Hello @hewigovens. We are also interested in consuming the Trust Wallet Core as a Swift Package. What is the current estimate on a timeline for the release of a package?

Thanks,
Erwin

**Comment by hewigovens** [comment]
@erwinmaza will work on it later this week, we have to build `SwiftProtobuf` as xcframework as well

**Comment by cbaies-bc** [comment]
Hey @hewigovens, do you have any updates on this?
It would be great if we could consume TrustWallet/wallet-core as a Swift Package.
We have been using a fork of your wallet-core-carthage solution, but since [enabling bitcode](https://github.com/trustwallet/wallet-core/pull/1438) in 2.6.8., the files are over 100 MB in size, and using Git LFS would be too costly.
Since building XCFrameworks in 2.6.6, the only blocker for creating the Swift Package would now be Swift Protobuf. I'm not sure why Apple didn't update the Readme, but I found it on the [Swift Package Registry](https://swiftpackageregistry.com/apple/swift-protobuf).
This should hopefully enable the creation of the Swift Package, but please let me know if I can help with this in any way.

Thanks,
Cosmin

**Comment by hewigovens** [comment]
@cbaies-bc we haven't migrated to SPM yet, so we don't release binaries for SPM, but you can try this test `Package.swift` here: https://github.com/hewigovens/wallet-core-spm,  run `tools/ios-xcframework` to build both frameworks

**Comment by simonmcl** [comment]
@hewigovens I've added the line to my swift package, mentioned in the repo you linked too, but I just get an error saying `invalid custom path 'Sources' for target 'WalletCore'` . Am I missing some other step?

**Comment by hewigovens** [comment]
@simonmcl sorry, I forget to push my local change, could you please try again?

**Comment by simonmcl** [comment]
@hewigovens that worked, amazing thank you!

FYI, for the README. It requires that you explicitly name the package when adding it as a dependency. so it looks like:

```
.package(name: "WalletCore", url: "https://github.com/hewigovens/wallet-core-spm", .branch("master")),
```

**Comment by josehidalgoromero** [comment]
I've been able to add SPM package as `.package(name: "WalletCore", url: "https://github.com/trustwallet/wallet-core.git", from: "2.6.36")` but I cannot add it as dependency:
```
.target(
            name: "CryptoModule",
            dependencies: [
                .product(name: "WalletCore", package: "WalletCore")
            ]),
```
What I'm missing?

**Comment by hewigovens** [comment]
@josehidalgoromero starting from `2.6.35`, we separate it to two libraries and upload the generated `Package.swift` to GitHub releases, will update readme later

Now you can download the `Package.swift` and put it into a local folder `WalletCore`, then use it as a local package like this:
```swift
.package(name: "WalletCore", path: "../WalletCore"),
```
