### ISSUE TITLE
[iOS] Build with Xcode 12 (Intel)

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1039]
It worked (Xcode 12 beta 4), will close it after Xcode GM

**Comment by ronaldmannak** [comment]
I believe this issue consists of two separate issues:
1. Building WalletCore on Xcode 12 beta on Intel
2. Building WalletCore on Xcode 12 beta on the DTK

Building on the DTK is a bigger challenge, since a number of brew and gem packages (including CocoaPods) don't work on the DTK at the moment. That means that bootstrap.sh nor any of the build scripts in tools work on ARM.

Since the ARM support of brew and gem packages is out of our hands, it would make sense to focus on adding support for Xcode 12 on Intel. Once the maintainers of the brew and gem dependencies catch up and add ARM support, it should be possible to build WalletCore on ARM without any further modifications.

**Comment by ronaldmannak** [comment]
A welcome addition would be to add a target for a universal (ARM/x64) Mac framework. With SwiftUI becoming more mature, a universal Mac framework would enable developers to have applications ready by the time the ARM Macs are introduced (end of 2020)

**Comment by hewigovens** [comment]
> Building WalletCore on Xcode 12 beta on Intel

This one is fixed, we can build with Xcode beta 12

**Comment by ronaldmannak** [comment]
@hewigovens Are you referring to PR #1040? Let me rerun bootstrap on beta 3 that was released today. #1040 didn't work on beta 2 (Intel).

**Comment by ronaldmannak** [comment]
Just checked, cmake trips over the space in the "Xcode-beta 2" filename (somehow the filename hasn't been updated for beta 3). You'll have run the build scripts using Xcode 11.

**Comment by ronaldmannak** [comment]
@hewigovens apologies, I think I know what you mean. Using Cocoapods (on Intel) you indeed use the framework on Xcode 12 beta (all betas).

**Comment by hewigovens** [comment]
created another issue to track building on DTK (yes, we got one :))

**Comment by saltyskip** [comment]
Any progress on this?

**Comment by hewigovens** [comment]
verified with Xcode 12 GM
