### ISSUE TITLE
[Ethereum/ABI] type bytes[] is encoded or decoded incorrectly

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1047]
I have created two test cases here: 

- https://github.com/trustwallet/wallet-core/pull/1044/files#diff-8e47f7546383013bb9c0ca5b76a9e2aeR161
- https://github.com/trustwallet/wallet-core/pull/1044/files#diff-db4d9e14ec181e5f1a2eddd7cff41b5fR530

**Comment by catenocrypt** [comment]
- ParamArray encode/decode was incorrect, in the case the array elements are dynamic (not simple types).
- getSize() method did not always return the same value as the actual encoded size.
--> These are solved with #1048 .
- Test ContractCall.Multicall is fixed by this.
- Test ParamArrayBytes: encoded size is now 896, which is the correct value, not 928.  The latter is obtained from online tool which wrapped the array in a collection.  So correct size of 896 is returned now.  Also added more tests: EthereumAbi.ParamArrayOfByteArray and EthereumAbi.DecodeFunctionContractMulticall for the same cases.
