### ISSUE TITLE
[Dash] Instant send support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1244]

**Comment by vikmeup** [comment]
Is this something should be done on the wallet core or blockbook node?

**Comment by hewigovens** [comment]
probably wallet core to set a flag somehow

**Comment by catenocrypt** [comment]
Based on this, it appears there is no need to do anything on the sender side any more.  As receiver?

"Since Dash 0.14, all user-facing interface options to create an InstantSend transaction have been removed, because all transactions are effectively InstantSend transactions. As before, the recipient is responsible for monitoring the network for the InstantSend lock and implementing user-facing logic and interfaces to continue with transaction processing after payment has been recieved. See the InstantSend Integration documentation for more information on how to monitor for InstandSend locks."
https://docs.dash.org/en/stable/wallets/dashcore/privatesend-instantsend.html
https://docs.dash.org/en/stable/developers/integration.html#is-broadcast

**Comment by catenocrypt** [comment]
@hewigovens , based on the above, it seems that no action is needed on send (every tx is treated as instantSend if possible), but action needed on atlas side to check if received tx is InstantSend locked, in which case there is no need to wait for confirmation.  But this second part is optional.
Should I transfer this issue to assets or close it?

https://github.com/dashpay/dash/blob/master/doc/instantsend.md#zmq
