### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by Ergus** [trustwallet/wallet-core#1344]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Fdroid is the best known foss apk source. Used on de-googled phones and custom roms like graphene, /e/ or linage without google services.

When using de-googled phones it is possible to download the trustwallet apk, but the updates are not so easy to get. Maintaining the script won't be complicated.

**Describe the solution you'd like**

All the steps to add an app to fdroid are here (they are extremely simple):

[Fdroid submit guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/)

After creating the submit files, the process can be automatized with a github action or Travis.

**Describe alternatives you've considered**

You could also maintain your own repo and add to fdroid 

**Additional context**

To add a repo of you want to maintain it independently the doc is here:

https://www.f-droid.org/en/tutorials/add-repo/

**Comment by vikmeup** [comment]
This repo for Wallet Core related issues. As of Android app it's not open source.

**Comment by 48-mq** [comment]
@vikmeup @rkokhatskyi @satoshiotomakan @Milerius  I'm no lawyer, but it seems to me that not having the Android app be open source would be a pretty clear violation of the conditions of the Apache 2.0 license that this entire project is covered by. Would you please clarify?

**Comment by Tpkilgore197** [comment]
Sure I can I am on a iPhone using a google crome extension with a open mit license Timothy P. KilgoreOn May 12, 2024, at 19:29, rcmc ***@***.***> wrote:﻿
@vikmeup @rkokhatskyi @satoshiotomakan @Milerius  I'm no lawyer, but it seems to me that not having the Android app be open source would be a pretty clear violation of the conditions of the Apache 2.0 license that this entire project is covered by. Would you please clarify?

**Comment by Tpkilgore197** [comment]
Any other stupid questions Mr attorney Timothy P. KilgoreOn May 12, 2024, at 19:29, rcmc ***@***.***> wrote:﻿
@vikmeup @rkokhatskyi @satoshiotomakan @Milerius  I'm no lawyer, but it seems to me that not having the Android app be open source would be a pretty clear violation of the conditions of the Apache 2.0 license that this entire project is covered by. Would you please clarify?

**Comment by Tpkilgore197** [comment]
I assume your the one that keeps changing my emails so I can’t log in Timothy P. KilgoreOn May 13, 2024, at 00:30, ***@***.*** wrote:﻿Any other stupid questions Mr attorney Timothy P. KilgoreOn May 12, 2024, at 19:29, rcmc ***@***.***> wrote:﻿
@vikmeup @rkokhatskyi @satoshiotomakan @Milerius  I'm no lawyer, but it seems to me that not having the Android app be open source would be a pretty clear violation of the conditions of the Apache 2.0 license that this entire project is covered by. Would you please clarify?

**Comment by Tpkilgore197** [comment]
You want to continue to do things outside the box and make new rules just because you think you know all the rules.   That’s fine I don’t mind a challenge but don’t be changing the thing that don’t belong to you cause I have changed it back two or three times now and you will find yourself in violation the next time    I suggest you quit trying to scam people and make money from it and when you get wrapped up and caught you want to be detrimental to the one that is on your scams and charge access    I highly suggest you stop Timothy P. KilgoreOn May 13, 2024, at 00:49, ***@***.*** wrote:﻿I assume your the one that keeps changing my emails so I can’t log in Timothy P. KilgoreOn May 13, 2024, at 00:30, ***@***.*** wrote:﻿Any other stupid questions Mr attorney Timothy P. KilgoreOn May 12, 2024, at 19:29, rcmc ***@***.***> wrote:﻿
@vikmeup @rkokhatskyi @satoshiotomakan @Milerius  I'm no lawyer, but it seems to me that not having the Android app be open source would be a pretty clear violation of the conditions of the Apache 2.0 license that this entire project is covered by. Would you please clarify?

**Comment by Milerius** [comment]
> @vikmeup @rkokhatskyi @satoshiotomakan @Milerius I'm no lawyer, but it seems to me that not having the Android app be open source would be a pretty clear violation of the conditions of the Apache 2.0 license that this entire project is covered by. Would you please clarify?

The Apache-2.0 license is a “permissive” license, which means that Apache-2.0 covered software components can be freely combined with proprietary software. It is perceived as enterprise-friendly, and for example used a lot by the Android project. When other people/companies modify the Apache-2.0 covered software they don't have to keep the same license (they can make their modified versions proprietary) but merely have to provide certain attribution notices. The Apache-2.0 does not require that anyone makes their source code available.

**Comment by 48-mq** [comment]
Thanks for the clarification @Milerius . I must say, I find this quite ironic given the name of the project.
