### ISSUE TITLE
Non-English and invalid passphrases

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#1607]
Current handling of non-English BIP39 passphrases (following #1601 #1599):

- Passphrase with English words:
validity is checked (based on dictionary), seed and entropy are generated, keys are generated.

- Passphrase with non-English words and invalid passphrases:
validity is not checked, seed is generated, entropy is empty, keys are generated.

**Comment by catenocrypt** [comment]
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

**Comment by catenocrypt** [comment]
Trust Wallet and wallet-core don't support non-English passphrases, nor is support planned.
Wallet-core is extended with an entry point to permit usage of non-English passphrases, see #1613.

One has to:
- validate the mnemonic against dictionary
- build the entropy bits from the indices of the mnemonic words
- create HDWallet with the mnemonic and entropy (wallet-core will not perform validity check)
- use HDWallet normally

See example `CreateFromMnemonicUnchecked`, https://github.com/trustwallet/wallet-core/pull/1613/files#diff-f0fba36710813b74e080a56e02b0aed0b88f4c3c24cad6b3a0e4d2e58cc3ebefR210

**Comment by catenocrypt** [comment]
Following alternatives to support non-Eng passphrase in some way (using custom dictionary #1611;  using only an unchecked wallet creation #1613), we decided not to support at all.  Validity check is being added, so non-English passphrases cannot be used.  Only English is supported.

**Comment by saltyskip** [comment]
@catenocrypt to handle accented characters and utf encoding issues we can use canonicalMapping to prevent this kind of problem. In swift code before creating HDWallet I use

```
mnemonic.joined(seperator: "").decomposedStringWithCanonicalMapping
```

Further documentation available here
https://developer.apple.com/documentation/foundation/nsstring/1409474-decomposedstringwithcanonicalmap?language=objc

Canonical mapping should be pushed into walletCore so that foreign language mnemonics can still be supported. Although it is now strongly discouraged by bip39 it is still needed for some wallets to support mnemonics that were generated in a foreign language.

https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#wordlists
