### ISSUE TITLE
Nano not visible

### ISSUE THREAD

**Issue by fcore117** [trustwallet/wallet-core#1836]
1: Use another Nano wallet, let faucets drop some coin. 2: Migrate seed to Trust Wallet, no coin. Simple to replicate.

**Comment by hewigovens** [comment]
Can you check if the address is same between two wallets?

**Comment by catenocrypt** [comment]
Which other Nano wallet?  Can you check if the address is same between two wallets?

**Comment by fcore117** [comment]
No address is not same, but what is point of seed if it looses funds? Mnemonic seed should be the ultimate "wallet" that do not depend what wallet is used. If it is so then Trust has no options to pick address that matches seed then please add option.

**Comment by catenocrypt** [comment]
A seed can be used to derive a large number of addresses, e.g. for different coins, or multiple ones for the same coin.
The so called derivation path is what governs how private key + address is derived for a coin.
For various reasons, not all wallets use the same derivation path, in which case they are not interoperable.
For Nano, Trust Wallet uses derivation path `"m/44'/165'/0'"`, which is supposed to be standard for Nano.

That's why I have asked what other wallet have you been using.

**Comment by fcore117** [comment]
Natrium, which is the most de-facto standard for Nano and 100% open. Perhaps then it would be wise to add some option to select derivation or some method so funds are easily interchangeable.  Currently  using seed to migrate between wallets could cause lot of confusion in future too for other users who think they have lost their funds.

**Comment by catenocrypt** [comment]
I've tried interoperability:
- Trust Wallet Nano wallet, import into Natrium --> not possible, as Natrium only accepts 24-word mnemonic, not 12
- Natrium wallet, import into Trust Wallet --> address is different

I could not find out derivation path used by Natrium.

Only one think is possible: to import Natrium wallet address as watch-only wallet into Trust Wallet.  This works.
