### ISSUE TITLE
Mac Catalyst missing support

### ISSUE THREAD

**Issue by shmakovigor** [trustwallet/wallet-core#1923]
Hello team. I have noticed that `WalletCoreCommon` framework doesn't include a slice for Mac Catalyst although slice for a regular macOS platform is presented. After inspecting the code I found that `/tools/ios-build` script has the configuration for building framework for Catalyst but never use it. Is there any issues with building this configuration? Catalyst apps are rapidly growing and it would be nice to make WalletCore available for them.

**Comment by hewigovens** [comment]
A few reasons: 
1. we believe Apple Silicon Macs will be major in the foreseeable future, just use iOS API + adopt iPad UI
2. It will increase binary size by another 25%, we did see a few times failed to upload binaries to GitHub after adding Mac binary 
3. Since Trust migrated to SPM, we're considering discontinue pod support in the future
