### ISSUE TITLE
My BNB Receiver address is - bnb1773k86dxwrc6kmu6zsfcatuu8mjl30n8a8ll86 Then I made transfer from crypto app funds are missing. Looks like trust wallet is not secure and like you to investigate.

### ISSUE THREAD

**Issue by vardikiran** [trustwallet/wallet-core#2091]
My BNB Receiver address is - bnb1773k86dxwrc6kmu6zsfcatuu8mjl30n8a8ll86
Then I made transfer from crypto app and I was looking at other apps and came back and checked. I saw that money which I was transferred from Crypto App 5.3 BNB 
After few minutes when I checked back the app my money was missing. and then realized it must be some app issue. How can a transaction happen without my notice. 
There was an unauthorized transaction & missing BNB happened within fraction of seconds.
I have not done this & I don't know who the recipient is. 
I want to request to clarify this and investigate and how can I take legal action against this through consumer court. 
Please reach me back on +16692120887 or vardikiran@gmail.com for any clarification

**Comment by catenocrypt** [comment]
Github issues are for development issues, closing.
Your issue may be a case of account compromise due to user-leaked secret.
Please contact customer support through regular channels:
https://support.trustwallet.com/en/support/home
https://trustwallet.com/

**Comment by BoggleSolutions** [comment]
Report scam to Boggle _solutions777 on IG or ‪+32 460 21 33 56‬ on WhatsApp for all |
BITCOIN RECOVERY | STOLEN CRYPTOS, INVESTMENT SCHEME SCAM | STOLEN NFT | NFT RECOVERY | Money Laundering, Cyber crime,Romance Scam, Fake ID and Forex trading scam, he has management tracking devices and software/tools to enable him track down any scammers from all over the world and also recover scammed money or bitcoin he's services are reliable and %100 guaranteed I assure you that. Dm now on instagram etc
IG (boggle_solutions777)
FB (Alexander Boggle) ( https://www.facebook.com/Alexander.boggle777)

**Comment by BoggleSolutions** [comment]
CONTACT 
![IMG_6114](https://user-images.githubusercontent.com/123510051/214409658-b76e7791-29bf-40e0-abc7-fe3d85abe575.PNG)
boggle_solutions777 ON INSTAGRAM FOR HELP

**Comment by JasperAdam** [comment]
Thank you for fixing my wallet, and volunteering your services and helping out in doing good and fighting against evil you are a super hero because you are more than a life saver to our family. We are thoroughly impressed by your work and the exceptional qualities you showed in a time of need. The rest of us here always look up to you for your dedication and work ethics. On behalf of the family we appreciate https://instagram.com/boggle_solutions777 on INSTAGRAM, thank you once again. I am dumfounded and surprised on how you recovered my 65k worth of Bitcoin. My family are happy and we truly appreciate your honesty Alex
