### ISSUE TITLE
Add support for Monero

### ISSUE THREAD

**Issue by BSathvik** [trustwallet/wallet-core#21]
Name: [Monero](https://www.getmonero.org/)
HD Derivation Scheme: Custom
Symbol: `XMR`

## Checklist

- [ ] Implement functionality in C++. Put it in a subfolder of `src/`.
    - [ ] Address (if necessary)
    - [ ] Transaction (if necessary)
    - [ ] Signer
- [ ] Write unit tests. Put them in a subfolder of `tests/`.
- [ ] Add relevant constants in `TWCoinType`, `TWP2SHPrefix`, `TWEthereymChainID`, `TWHRP`, etc., as necessary.
- [ ] Return correct curve and purpose in `src/Coin.cpp`.
- [ ] Implement address validation and derivation in `src/Coin.cpp`.
- [ ] Implement coin configuration `src/include/TWCoinTypeConfiguration.cpp`.
- [ ] Write interface header in `include/TrustWalletCore` and implement the interface in `src/interface`.
    - [ ] Address interface (if necessary).
    - [ ] Signing interface.
- [ ] Validate generated code in Android an iOS projects. Write integration tests for each.

**Comment by dEBRUYNE-1** [comment]
First of all, thank you for trying to add Monero!

I just wanted to add a few notes:

>* coin type / decimals

Note that Monero has twelve decimal places, which is different from most other coins. 

>* recommended block explorer

I've personally observed that [XMRchain](https://xmrchain.net/) is more stable. I suppose you could use either one as default and use the other as backup. 

>* Account / Address

You can also find some decent info here on how Monero addresses are generated:

https://xmr.llcoins.net/addresstests.html

^ This tool was made by one of the Monero core-team members. 

If you have any specific questions, I'd suggest to simply post them here on this Github issue, because it allows me to easily provide a link to the Monero developers.

**Comment by rbrunner7** [comment]
I recently did an analysis what it would take to integrate Monero as an additional currency into OpenBazaar. You can find it [here](https://rbrunner7.github.io/openbazaar). It's only a partial overlap with your task of course, but you may still find the following chapters there interesting for a first high-level overview and some links:

* Monero Wallets
* monero-wallet-rpc
* Access to the Monero Network

In any case, I would say prepare yourself mentally for a quite challenging job :)

**Comment by hewigovens** [comment]
Cake Wallet is a open source XMR wallet (https://github.com/fotolockr/CakeWallet), maybe a good reference

**Comment by rbrunner7** [comment]
> Cake Wallet is a open source XMR wallet (https://github.com/fotolockr/CakeWallet), maybe a good reference

I think unfortunately this isn't the case because CakeWallet, being a XMR-only wallet, can directly use the "original" Monero codebase, whereas TrustWallet / wallet-core have very different requirements and separation of functionality and therefore probably can't.

wallet-core asks for "pure" transaction construction code (plus unit tests) which, in this form, is nowhere to be found in the Monero code: There transaction construction mingles with code to access the network and other sub-tasks, and untangling that is quite some work.

**Comment by mrrovot** [comment]
What is the state of this?, this would be awesome.

**Comment by rbrunner7** [comment]
For better visibility I copy over a little analysis of the situation and the job at hand that I wrote on Telegram on March 4. Interestingly it evoked almost no reactions there, not even simple ones like "What? So much work?" ...

-----

rbrunner7, [04.03.19 20:06]
Sooo ... over this weekend I had a look a the code in the "original" Monero C++ codebase that builds transactions. I did not go very deep, I just wanted to get a rough overview what it would mean to re-build that code for wallet-core.

That code is so interwoven with code that fetches transactions for building rings, with code that uses other things from the network to estimate fees, etc, that I would say a solid strategy would be analyse that code until fully understanding it, and then re-build the tx construction code more or less from scratch.

Or, in other words, I don't think it makes sense to lift big portions of the code out of there and then starting to re-work and refactor from there.

I see the time needed for that, together with the time to write comprehensive unit tests, amount to several full work weeks. If I add to this the time needed for the code to interact with the Monero blockchain outside of wallet-core, I arrive at a very rough estimate for the complete XMR integration in TrustWallet of 4 to 6 full work months.

rbrunner7, [04.03.19 21:04]
And, well, before anybody misunderstands: This is *not* me asking anybody to pay me 4 to 6 months, or anything similar, really just an attempt of an work amount estimate that somebody may find useful. I myself have a day job that I can't and don't want to leave, so I am in no position to provide so many months of work within any reasonable number of calendar months even if I made this priority #1 for my Monero-related work ...

**Comment by dEBRUYNE-1** [comment]
@BSathvik @vikmeup - Would you perhaps be able to provide an update? 

Also, if you have any specific questions for Monero developers, please let me know.

**Comment by BroManDudeGuyPhD** [comment]
Is this being worked on still?

**Comment by hewigovens** [comment]
@dEBRUYNE-1 @BroManDudeGuyPhD XMR is on hold right now

**Comment by dEBRUYNE-1** [comment]
@hewigovens - Thanks for the update.

**Comment by vikmeup** [comment]
Closing for now, not able to find anyone in the community to implement xmr support

**Comment by prefix309** [comment]
Coinomi supports Monero too.

**Comment by yslpn** [comment]
Let's reopen it?

**Comment by socksprox** [comment]
Has this been forgotten?

**Comment by satoshiotomakan** [comment]
Hi @socksprox, we don't have a plan to add Monero chain at the moment. We'll post an update if there is one
