### ISSUE TITLE
[Cosmos] Add signDirect support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2412]
Sample request from WalletConnect v2:

```shell
Request(id: 1658838935518990, topic: "5c2465c7739be776ba3616754d917aa715562d0c0d5872819095fbdc78794a2e", method: "cosmos_signDirect", params: AnyCodable: "{"signDoc":{"accountNumber":"1","authInfoBytes":"0a0a0a0012040a020801180112130a0d0a0575636f736d12043230303010c09a0c","bodyBytes":"0a90010a1c2f636f736d6f732e62616e6b2e763162657461312e4d736753656e6412700a2d636f736d6f7331706b707472653766646b6c366766727a6c65736a6a766878686c63337234676d6d6b38727336122d636f736d6f7331717970717870713971637273737a673270767871367273307a716733797963356c7a763778751a100a0575636f736d120731323334353637","chainId":"cosmoshub-4"},"signerAddress":"cosmos1y2x5mxc6h7slvptdg8z6h44me3pmdcefucsv36"}", chainId: cosmos:cosmoshub-4)
```

`bodyBytes` and `authInfoBytes` are prepared already

**Comment by catenocrypt** [comment]
Parsing the serialized `bodyBytes` is difficult, due to the `protobuf.Any` types used (for messages in `TxBody`).

For info: the above example contains a `MsgSend` (`cosmos.bank.v1beta1.MsgSend`), with parameters:
`cosmos1pkptre7fdkl6gfrzlesjjvhxhlc3r4gmmk8rs6` `cosmos1qypqxpq9qcrsszg2pvxq6rs0zqg3yyc5lzv7xu` `ucosm` `1234567`

**Comment by hewigovens** [comment]
@catenocrypt it looks we can try a few known msg types to decode? we can also ask dapp to pass the original msg in json format

**Comment by AyushBherwani1998** [comment]
@hewigovens @catenocrypt should we add test cases for Swift & Kotlin?
