### ISSUE TITLE
Allow to add custom memo for THORChain Swap transactions

### ISSUE THREAD

**Issue by ArtemGoryunov** [trustwallet/wallet-core#2713]
**Is your feature request related to a problem? Please describe.**
Current implementation of [THORChain Swap transactions](https://github.com/trustwallet/wallet-core/pull/1371) doesn't allow to define memo value. For example, it can be used for enable affiliate fee. 

**Describe the solution you'd like**
That memo should be added to the end of the memo of transaction.

**Describe alternatives you've considered**
None

**Resources**

https://medium.com/thorchain/affiliate-fees-on-thorchain-17cbc176a11b

**Comment by catenocrypt** [comment]
Some concerns:
- Should there be a way to add custom additional memo, or structured info `feeaddress:feerate`?  Since spec explicitly mentions this structure, structured info (`feeaddress`, `feerate`) is better.
- In some chains the length of the memo is limited, this (quite long) extra may cause issues.

**Comment by oxyc** [comment]
> In some chains the length of the memo is limited, this (quite long) extra may cause issues.

[thornames](https://docs.thorchain.org/network/thorchain-name-service) for the affiliate address helps with this.

Note there are technically more parameters than these since dex aggregator was added to TC: https://dev.thorchain.org/thorchain-dev/aggregators/memos
