### ISSUE TITLE
[BITCODE] Can't archive the project

### ISSUE THREAD

**Issue by datsafemoon** [trustwallet/wallet-core#2853]
Hi,

I am using version 3.1.7. I can run a project but when I try to archive am getting error related to bitcode. I removed DerivedData folder. I can only archive the project when I disable Bitcode of TrustWallerCode pod. This is the problem I had when I upgraded version 2.7.2 -> 3.1.7. It was fine with me before

My error: /Users/macbookpro/Library/Developer/Xcode/DerivedData/SafemoonWallet-bfvbtwcvjzbeclazmuevlwokapeh/Build/Intermediates.noindex/ArchiveIntermediates/SafemoonWallet/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/TrustWalletCore/Core/WalletCoreCommon.framework/WalletCoreCommon(TWAES.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

Am using Xcode version - 13.4.1

**Comment by Milerius** [comment]
> Hi,
> 
> I am using version 3.1.7. I can run a project but when I try to archive am getting error related to bitcode. I removed DerivedData folder. I can only archive the project when I disable Bitcode of TrustWallerCode pod. This is the problem I had when I upgraded version 2.7.2 -> 3.1.7. It was fine with me before
> 
> My error: /Users/macbookpro/Library/Developer/Xcode/DerivedData/SafemoonWallet-bfvbtwcvjzbeclazmuevlwokapeh/Build/Intermediates.noindex/ArchiveIntermediates/SafemoonWallet/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/TrustWalletCore/Core/WalletCoreCommon.framework/WalletCoreCommon(TWAES.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
> 
> Am using Xcode version - 13.4.1

Hello @datsafemoon - thanks for openning the issue.

Bitcode has been deprecated by apple: https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes

"Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: “Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode.” The capability to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped before being submitted to the App Store. Debug symbols can only be downloaded from App Store Connect / TestFlight for existing bitcode submissions and are no longer available for submissions made with Xcode 14. (86118779)"

You need to disable bitcode for all your targets in order to build recent version of wallet-core - this is a change initiated in: https://github.com/trustwallet/wallet-core/releases/tag/3.1.6

Please let me know if u have more questions.

**Comment by datsafemoon** [comment]
Thank you for your help
