### ISSUE TITLE
ABI encoder fails with max Uint256 value

### ISSUE THREAD

**Issue by vcoolish** [trustwallet/wallet-core#3639]
lib version: 4.0.15

``` kotlin
tokens = "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff".hexToBigIntegerOrZero()
val function = EthereumAbiFunction("approve")
function.addParamAddress(spender.data, false)
function.addParamUInt256(tokens.toByteArray(), false)
return EthereumAbi.encode(function)
```
returns empty byte array

**Comment by satoshiotomakan** [comment]
Hi @vcoolish, I tested the code, and I couldn't reproduce the issue with UInt256. The problem can be related to an invalid address data. Could you please check what value you pass as `spender.data`?
The code that works for me:
```kotlin
val function = EthereumAbiFunction("approve")
        // add params
        val tokens = "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff".hexToBigIntegerOrZero()
        assertEquals(0, function.addParamAddress("f784682c82526e245f50975190ef0fff4e4fc077".toHexByteArray(), false))
        assertEquals(1, function.addParamUInt256(tokens.toByteArray(), false))
        // encode
        val encoded = EthereumAbi.encode(function)
        assertEquals("0x095ea7b3000000000000000000000000f784682c82526e245f50975190ef0fff4e4fc0770000000000000000000000000000000000000000000000000000000000000000",
            Numeric.toHexString(encoded))
```

**Comment by satoshiotomakan** [comment]
Didn't notice.
I copied the `hexToBigIntegerOrZero()` function from Android repo and made a small issue:
https://github.com/trustwallet/android/blob/59a7f9863cb23e0b438494c9f6d21836e1ea7143/blockchain/src/main/java/trust/blockchain/util/Numbers.kt#L30-L34

Anyway, the problem you have is that `"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff".hexToBigIntegerOrZero().toByteArray()` returns 65 bytes `[0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]`, but expected without the leading `0` byte.
So in Rust implementation we have a strict check that `UInt256` binary representation has <= 64 bytes.

Is there a chance to make a fix on the end-user app, because it can be not obvious if WalletCore just ignore the extra bytes.

**Comment by vcoolish** [comment]
thanks will handle on client side
