### ISSUE TITLE
Memory leak detection tools

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#374]
e.g. Valgrind

**Comment by alejandro-isaza** [comment]
Valgrind doesn't work on latest version of macOS. Even running on Linux I didn't find it very useful because it would only check for leaks in the test code. I think it is more valuable to run memory tools on the target platform. For instance Xcode has Address Sanitizer which will catch C++ memory problems as well as Swift. I believe Android also has memory debugging tools.
