### ISSUE TITLE
iOS Trust Wallet App Not Interacting Correctly with Smart Contracts Since Last Two Updates

### ISSUE THREAD

**Issue by mcljs** [trustwallet/wallet-core#3746]
**Describe the bug**
Since the last two updates of the Trust Wallet app on iOS devices, the app is no longer able to interact correctly with smart contracts, specifically when attempting to read contract data such as using the balanceOf method. This issue results in a CALL_EXCEPTION error with no data returned (data="0x"). This behavior is not observed on Android devices or desktop web browser extensions, where the app functions as expected.

**To Reproduce**

1. Connect Trust Wallet (iOS version) to a DApp using WalletConnect.
2. Attempt to query the balanceOf method of a smart contract (e.g., an ERC20 token contract).
3. Observe the error returned, indicating a failure to read from the contract.

**Expected behavior**
The expected behavior is for the Trust Wallet app on iOS to successfully interact with the smart contract and return the correct balance data without throwing a CALL_EXCEPTION error. This is consistent with the behavior observed on Android devices and desktop web browser extensions.

**Screenshots**
N/A (I do not have screenshots available, but the error log is provided below for reference).

```json
{
  "reason": null,
  "code": "CALL_EXCEPTION",
  "method": "balanceOf(address)",
  "data": "0x",
  "errorArgs": null,
  "errorName": null,
  "errorSignature": null,
  "address": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
  "args": ["0x2B119E9023DBcBC29E33b994E816A843aAA9C9aC"],
  "transaction": {
    "data": "0x70a082310000000000000000000000002B119E9023DBcBC29E33b994E816A843aAA9C9aC",
    "to": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
    "from": "0x2B119E9023DBcBC29E33b994E816A843aAA9C9aC"
  }
}
```

The issue has been occurring since the last two updates of the Trust Wallet app on iOS. The same operations perform as expected without any issues on Android devices and through desktop web browser extensions. This suggests that the issue is specific to the iOS version of the Trust Wallet app.

**Comment by satoshiotomakan** [comment]
Hi @mcljs, thank you for the report!
@gastonm5, could you please take a look at the issue?

**Comment by gastonm5** [comment]
Hello @mcljs ! Do you have any example dapp where you're seeing this issue?

**Comment by mcljs** [comment]
> Hello @mcljs ! Do you have any example dapp where you're seeing this issue?

You can see in this https://www.newstarworld.com/

**Comment by wilsommary676** [comment]
I tried investing in Cryptocurrency Via a trading Platform, I studied the platform and invested some money in it and I was advised to deposit more to be able to receive some additional profits, The honest truth is that I would never do cryptocurrency, but due to how it profitable and lost if stuff I thought I could earn from it as well, I deposited all I had and it all turned from something exciting to something Heartbreaking I was denied access to my money, I couldn’t withdraw they took everything I had just in a blink of an eye,I then later Found out it possible to get what you lost via crypto and in assets too back. I then search on how i could take the step of getting what they took from me back and then I found Market peace recovery they are an Elite Funds recovery company and they got me out of the mess I was in, not just by recovering my money but they also recovered my assets. This is a Fund Recovery and Legal you can talk to them ease the pain you feeling and get everything you lost back. There is a way to get all what you lost back just talk to Quest Finance For Help and Guidance. Email on Jeffsilbert 39 gmail com

**Comment by Milerius** [comment]
This issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
