### ISSUE TITLE
B

### ISSUE THREAD

**Issue by Hadi90Ahmed** [trustwallet/wallet-core#3836]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Tpkilgore197** [comment]
The fact that my coins was in my wallet and they have been moved Timothy P. KilgoreOn May 12, 2024, at 01:21, Hadi90Ahmed ***@***.***> wrote:﻿
Describe the bug
A clear and concise description of what the bug is.
To Reproduce
Steps to reproduce the behavior:
Expected behavior
A clear and concise description of what you expected to happen.
Screenshots
If applicable, add screenshots to help explain your problem.
Additional context
Add any other context about the problem here.
