### ISSUE TITLE
Add ethereum abi support

### ISSUE THREAD

**Issue by madcake** [trustwallet/wallet-core#573]
Some doc, with complete list of argument types:
https://eth.wiki/en/ethereum-contract-abi

https://github.com/TrustWallet/trust-core/blob/master/Sources/Ethereum/Solidity/ABIEncoder.swift

**Comment by catenocrypt** [comment]
Preparation work: decode support added, PR #703 merged.

**Comment by catenocrypt** [comment]
@hewigovens Update: C interface cause some trouble: a void* handle (as it is done for TWString, TWData) does not work for Function<T> type, because template parametrization is lost with void* conversion and back.  After some consideration I have decided to make a non-templated version of Function, vector<ParameterBase*> instead of Tuple template parameters.
See:  https://github.com/catenocrypt/trust-wallet-core/blob/573-proto/src/Ethereum/ABI/FunctionNG.h

**Comment by catenocrypt** [comment]
Update:
* Encode/decode reworked to rely less on templates, for types that will go though JNI.
* C interface added (with tests)
* JNI interface added.
* on branch 573-c-iface .
Next steps:
* Tests in wallet-core android part (kotlin)
* Validate with android project, that it can switch from web3j to wallet-core, e.g. with KyberNet.

**Comment by hewigovens** [comment]
Feel free to open a wip pull request

**Comment by catenocrypt** [comment]
Ready, waiting for merge (PR #712 ).
For usage, see test case testEthereumAbiEncoderEncodeFuncCase1 from TestEthereumTransactionSigner.kt .
