### ISSUE TITLE
Split TWCoinTypeConfigTests into small files

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#694]
`TWCoinTypeConfigTests` becomes quite big now, easy to cause conflicts when adding multiple new coins, we can split it into small files and put them under each blockchain folder.

we can also replace dummy tx id `123` to real tx id

**Comment by catenocrypt** [comment]
Proposed steps:
- Update TWCoinTypeConfigTests to be in sync with current coins.json
- Reorganize such that instead of test cases per use case (about 8) there should be test cases per coin, containing all use cases
- Split the tests in separate files, one per coin

A helper script is probably useful.  I start working on this.

**Comment by hewigovens** [comment]
Don't forget to update the documents: https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-definitions

**Comment by catenocrypt** [comment]
PRs #696 and https://github.com/trustwallet/developer/pull/60 merged, one leftover: update branch ton-address.
